### ISSUE TITLE
TODO:frontend

### ISSUE THREAD

**Issue by ChristopherRoy1** [ChristopherRoy1/mchacks2018#2]
- [x] Text Editor Skeleton
- [ ] Font Functionality/Size
- [ ] Bold/Italic/Underline
- [ ] Bullet/Numbering
- [ ] Saving Button
- [ ] Playback Pane
- [ ] Recording Pane
- [ ] Note/Recording Frame
- [ ] Playback Frame 
- [ ] Startup Frame
